version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: insightly-svc
      runtime: docker
      repo: https://github.com/hivelai/insightly-svc
      branch: release-render
      plan: standard
      region: singapore
      dockerContext: .
      dockerfilePath: ./Dockerfile
      autoDeployTrigger: commit

    - type: web
      name: insightly-ui
      runtime: docker
      repo: https://github.com/hivelai/insightly-ui
      branch: release-render
      plan: standard
      region: singapore
      dockerContext: .
      dockerfilePath: ./Dockerfile
      autoDeployTrigger: commit

previews:
  generation: automatic
  expireAfterDays: 1